DATA:
  img_size: [1, 50, 50]
  rgb: True
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene.h5
TRAINING:
  ENCODER:
    name: VGG16Encoder
    learning_rate: 0.0001
  MODEL:
    name: DummyCNN
    learning_rate: 0.001
  batch_size: 64
  epochs: 10
  num_units: 9