DATA:
  img_shape: [1, 50, 50]
  rgb: True
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene.h5
TRAINING:
  ENCODER:
    name: VGG16Encoder
    freeze: True
    learning_rate: 0.0001
  PREDICTOR:
    name: DummyCNN
    learning_rate: 0.001
  batch_size: 64
  epochs: 10
  num_units: 9
  early_stopping: False
  early_stopping_patience: 5
  save_logs: True
TESTING:
  batch_size: 64
  weights: "best.pth"
  metrics: ["mae", "mse"]
  save_logs: True