DATA:
  img_size: [1, 50, 50]
  rgb: False
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene.h5
TRAINING:
  ENCODER:
    name: VGG16Encoder
    learning_rate: 0.001
  PREDICTOR:
    name: DummyCNN
    learning_rate: 0.001
  batch_size: 64
  epochs: 100
  num_units: 9
  early_stopping: True
  early_stopping_patience: 7
  save_logs: True
TESTING:
  batch_size: 64
  weights: "best.pth"
  metrics: ["mae", "mse"]
  save_logs: True