DATA:
  data_handler: H5SeqDataset # "H5Dataset", "H5SeqDataset", "BaselineRGBDataset", "BaselineSeqRGBDataset"
  img_shape: [1, 50, 50]
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene.h5
  response_type: firing_rate_10ms
  is_rgb: True
  seq_len: 16
  prediction_step: 0
TRAINING:
  ENCODER:
    name: VGG16Encoder
    weights: vgg16-397923af.pth
    freeze: False
    learning_rate: 0.0001
  PREDICTOR:
    name: SingleLSTM
    learning_rate: 0.001
  batch_size: 16
  epochs: 100
  num_units: 9
  early_stopping: True
  early_stopping_patience: 5
  save_logs: True
TESTING:
  batch_size: 16
  weights: "best.pth"
  metrics: ["mae", "mse"]
  save_logs: True
  run_on_test_data: True
  run_on_train_data: True