DATA:
  img_shape: [1, 50, 50]
  rgb: False
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene.h5
  seq_len: 8
TRAINING:
  ENCODER:
    name: CustomEncoder
    weights: fc_encoder_best.pth
    freeze: True
    learning_rate: 0.0001
  PREDICTOR:
    name: SingleLSTM
    learning_rate: 0.001
  batch_size: 128
  epochs: 150
  num_units: 9
  early_stopping: True
  early_stopping_patience: 5
  save_logs: True
TESTING:
  batch_size: 128
  weights: "best.pth"
  metrics: ["mae", "mse"]
  save_logs: True
  run_on_train_data: True