DATA:
  img_shape: [1, 50, 50]
  rgb: True
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene.h5
  seq_len: 16
TRAINING:
  ENCODER:
    name: MC3VideoEncoder
    weights: mc3-18.pth
    freeze: False
    learning_rate: 0.00001
  PREDICTOR:
    name: DummyCNN
    learning_rate: 0.001
  batch_size: 32
  epochs: 10
  num_units: 9
  early_stopping: True
  early_stopping_patience: 3
  save_logs: True
TESTING:
  batch_size: 16
  weights: "best.pth"
  metrics: ["mae", "mse"]
  save_logs: True
  run_on_train_data: True