DATA:
  data_handler: H5SeqDataset
  img_shape: [1, 50, 50]
  is_rgb: False
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene.h5
  response_type: firing_rate_10ms
  seq_len: 8
  prediction_step: 0
  subset_size: 2000
TRAINING:
  ENCODER:
    name: CustomEncoder
    weights: custom_encoder_best_convdense.pth
    freeze: False
    learning_rate: 0.00001
  PREDICTOR:
    name: SimpleCFC
    learning_rate: 0.0001
  batch_size: 32
  epochs: 10
  num_units: 9
  early_stopping: True
  early_stopping_patience: 5
  save_logs: True
TESTING:
  batch_size: 32
  weights: "best.pth"
  metrics: ["mae", "mse"]
  save_logs: True
  run_on_train_data: True