DATA:
  data_handler: BaselineRGBDataset
  img_shape: [40, 50, 50]
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene.h5
  response_type: firing_rate_10ms
  is_rgb: False
  seq_len: 0
  subseq_len: 40
  prediction_step: 1
  subset_size: 2000
TRAINING:
  ENCODER:
    name: OgEncoder
    weights: None
    freeze: False
    learning_rate: 0.0001
  PREDICTOR:
    name: OgLinear
    learning_rate: 0.001
  batch_size: 16
  epochs: 1
  num_units: 9
  early_stopping: False
  early_stopping_patience: 5
  save_logs: True
TESTING:
  batch_size: 16
  weights: "best.pth"
  metrics: ["mae", "mse"]
  save_logs: True
  run_on_test_data: True
  run_on_train_data: True