hydra:
  run:
    dir: results/test_hydra_mse
defaults:
  - _self_
  - curriculum/curriculum-schedule
  - override hydra/job_logging: disabled # disable hydra logging
data:
  data_handler: H5SeqDataset
  img_dim: 50 # Spatial dimension of the input image
  path: data/neural_code_data/ganglion_cell_data/15-10-07/naturalscene_with_val.h5
  response_type: firing_rate_10ms
  is_rgb: True
  seq_len: 16
  subseq_len: 3
  window_overlap: 0
  prediction_step: 1
  subset_size: -1
  num_units: 9
  pred_channels: all
  is_classification: False
  class_epsilon: 0.001
training:
  is_curriculum: False
  debug_mode: True
  loss_function: mse
  encoder:
    name: MC3VideoEncoder
    weights: null
    freeze: True
    learning_rate: 0.00001
  predictor:
    name: MultiLinear
    learning_rate: 0.001
    weights: null
    hidden_size: 64
    activation: relu
  batch_size: 1024
  epochs: 40
  early_stopping: True
  early_stopping_patience: 5
  save_logs: True
testing:
  batch_size: 1024
  weights: "best.pth"
  metrics: ["mae", "mse"]
  save_logs: True
  run_on_test_data: True
  run_on_train_data: True